CREATE KEYSPACE is_keyspace
WITH replication = {
  'class': 'SimpleStrategy',
  'replication_factor': 3
};

CREATE TABLE is_keyspace.dbgen_version (
    dv_version TEXT,
    dv_create_date DATE,
    dv_create_time TIME,
    dv_cmdline_args TEXT,
    primary key(dv_version)
);

CREATE TABLE is_keyspace.customer_address (
    ca_address_sk INT,
    ca_address_id TEXT,
    ca_street_number TEXT,
    ca_street_name TEXT,
    ca_street_type TEXT,
    ca_suite_number TEXT,
    ca_city TEXT,
    ca_county TEXT,
    ca_state TEXT,
    ca_zip TEXT,
    ca_country TEXT,
    ca_gmt_offset DECIMAL,
    ca_location_type TEXT,
    PRIMARY KEY (ca_address_sk)
);

CREATE TABLE is_keyspace.customer_demographics (
    cd_demo_sk INT,
    cd_gender TEXT,
    cd_marital_status TEXT,
    cd_education_status TEXT,
    cd_purchase_estimate INT,
    cd_credit_rating TEXT,
    cd_dep_count INT,
    cd_dep_employed_count INT,
    cd_dep_college_count INT,
    PRIMARY KEY (cd_demo_sk)
);

CREATE TABLE is_keyspace.date_dim (
    d_date_sk INT,
    d_date_id TEXT,
    d_date DATE,
    d_month_seq INT,
    d_week_seq INT,
    d_quarter_seq INT,
    d_year INT,
    d_dow INT,
    d_moy INT,
    d_dom INT,
    d_qoy INT,
    d_fy_year INT,
    d_fy_quarter_seq INT,
    d_fy_week_seq INT,
    d_day_name TEXT,
    d_quarter_name TEXT,
    d_holiday TEXT,
    d_weekend TEXT,
    d_following_holiday TEXT,
    d_first_dom INT,
    d_last_dom INT,
    d_same_day_ly INT,
    d_same_day_lq INT,
    d_current_day TEXT,
    d_current_week TEXT,
    d_current_month TEXT,
    d_current_quarter TEXT,
    d_current_year TEXT,
    PRIMARY KEY (d_date_sk)
);

CREATE TABLE is_keyspace.warehouse (
    w_warehouse_sk INT,
    w_warehouse_id TEXT,
    w_warehouse_name TEXT,
    w_warehouse_sq_ft INT,
    w_street_number TEXT,
    w_street_name TEXT,
    w_street_type TEXT,
    w_suite_number TEXT,
    w_city TEXT,
    w_county TEXT,
    w_state TEXT,
    w_zip TEXT,
    w_country TEXT,
    w_gmt_offset DECIMAL,
    PRIMARY KEY (w_warehouse_sk)
);

CREATE TABLE is_keyspace.ship_mode (
    sm_ship_mode_sk INT,
    sm_ship_mode_id TEXT,
    sm_type TEXT,
    sm_code TEXT,
    sm_carrier TEXT,
    sm_contract TEXT,
    PRIMARY KEY (sm_ship_mode_sk)
);

CREATE TABLE is_keyspace.time_dim (
    t_time_sk INT,
    t_time_id TEXT,
    t_time INT,
    t_hour INT,
    t_minute INT,
    t_second INT,
    t_am_pm TEXT,
    t_shift TEXT,
    t_sub_shift TEXT,
    t_meal_time TEXT,
    PRIMARY KEY (t_time_sk)
);

CREATE TABLE is_keyspace.reason (
    r_reason_sk INT,
    r_reason_id TEXT,
    r_reason_desc TEXT,
    PRIMARY KEY (r_reason_sk)
);

CREATE TABLE is_keyspace.income_band (
    ib_income_band_sk INT,
    ib_lower_bound INT,
    ib_upper_bound INT,
    PRIMARY KEY (ib_income_band_sk)
);

CREATE TABLE is_keyspace.item (
    i_item_sk INT,
    i_item_id TEXT,
    i_rec_start_date DATE,
    i_rec_end_date DATE,
    i_item_desc TEXT,
    i_current_price DECIMAL,
    i_wholesale_cost DECIMAL,
    i_brand_id INT,
    i_brand TEXT,
    i_class_id INT,
    i_class TEXT,
    i_category_id INT,
    i_category TEXT,
    i_manufact_id INT,
    i_manufact TEXT,
    i_size TEXT,
    i_formulation TEXT,
    i_color TEXT,
    i_units TEXT,
    i_container TEXT,
    i_manager_id INT,
    i_product_name TEXT,
    PRIMARY KEY (i_item_sk)
);

CREATE TABLE is_keyspace.store (
    s_store_sk INT,
    s_store_id TEXT,
    s_rec_start_date DATE,
    s_rec_end_date DATE,
    s_closed_date_sk INT,
    s_store_name TEXT,
    s_number_employees INT,
    s_floor_space INT,
    s_hours TEXT,
    s_manager TEXT,
    s_market_id INT,
    s_geography_class TEXT,
    s_market_desc TEXT,
    s_market_manager TEXT,
    s_division_id INT,
    s_division_name TEXT,
    s_company_id INT,
    s_company_name TEXT,
    s_street_number TEXT,
    s_street_name TEXT,
    s_street_type TEXT,
    s_suite_number TEXT,
    s_city TEXT,
    s_county TEXT,
    s_state TEXT,
    s_zip TEXT,
    s_country TEXT,
    s_gmt_offset DECIMAL,
    s_tax_precentage DECIMAL,
    PRIMARY KEY (s_store_sk)
);

CREATE TABLE is_keyspace.call_center (
    cc_call_center_sk INT,
    cc_call_center_id TEXT,
    cc_rec_start_date DATE,
    cc_rec_end_date DATE,
    cc_closed_date_sk INT,
    cc_open_date_sk INT,
    cc_name TEXT,
    cc_class TEXT,
    cc_employees INT,
    cc_sq_ft INT,
    cc_hours TEXT,
    cc_manager TEXT,
    cc_mkt_id INT,
    cc_mkt_class TEXT,
    cc_mkt_desc TEXT,
    cc_market_manager TEXT,
    cc_division INT,
    cc_division_name TEXT,
    cc_company INT,
    cc_company_name TEXT,
    cc_street_number TEXT,
    cc_street_name TEXT,
    cc_street_type TEXT,
    cc_suite_number TEXT,
    cc_city TEXT,
    cc_county TEXT,
    cc_state TEXT,
    cc_zip TEXT,
    cc_country TEXT,
    cc_gmt_offset DECIMAL,
    cc_tax_percentage DECIMAL,
    PRIMARY KEY (cc_call_center_sk)
);

CREATE TABLE is_keyspace.customer (
    c_customer_sk INT,
    c_customer_id TEXT,
    c_current_cdemo_sk INT,
    c_current_hdemo_sk INT,
    c_current_addr_sk INT,
    c_first_shipto_date_sk INT,
    c_first_sales_date_sk INT,
    c_salutation TEXT,
    c_first_name TEXT,
    c_last_name TEXT,
    c_preferred_cust_flag TEXT,
    c_birth_day INT,
    c_birth_month INT,
    c_birth_year INT,
    c_birth_country TEXT,
    c_login TEXT,
    c_email_address TEXT,
    c_last_review_date TEXT,
    PRIMARY KEY (c_customer_sk)
);

CREATE TABLE is_keyspace.web_site (
    web_site_sk INT,
    web_site_id TEXT,
    web_rec_start_date DATE,
    web_rec_end_date DATE,
    web_name TEXT,
    web_open_date_sk INT,
    web_close_date_sk INT,
    web_class TEXT,
    web_manager TEXT,
    web_mkt_id INT,
    web_mkt_class TEXT,
    web_mkt_desc TEXT,
    web_market_manager TEXT,
    web_company_id INT,
    web_company_name TEXT,
    web_street_number TEXT,
    web_street_name TEXT,
    web_street_type TEXT,
    web_suite_number TEXT,
    web_city TEXT,
    web_county TEXT,
    web_state TEXT,
    web_zip TEXT,
    web_country TEXT,
    web_gmt_offset DECIMAL,
    web_tax_percentage DECIMAL,
    PRIMARY KEY (web_site_sk)
);

CREATE TABLE is_keyspace.store_returns (
    sr_returned_date_sk INT,
    sr_return_time_sk INT,
    sr_item_sk INT,
    sr_customer_sk INT,
    sr_cdemo_sk INT,
    sr_hdemo_sk INT,
    sr_addr_sk INT,
    sr_store_sk INT,
    sr_reason_sk INT,
    sr_ticket_number INT,
    sr_return_quantity INT,
    sr_return_amt DECIMAL,
    sr_return_tax DECIMAL,
    sr_return_amt_inc_tax DECIMAL,
    sr_fee DECIMAL,
    sr_return_ship_cost DECIMAL,
    sr_refunded_cash DECIMAL,
    sr_reversed_charge DECIMAL,
    sr_store_credit DECIMAL,
    sr_net_loss DECIMAL,
    PRIMARY KEY (sr_item_sk, sr_ticket_number)
);

CREATE TABLE is_keyspace.household_demographics (
    hd_demo_sk INT,
    hd_income_band_sk INT,
    hd_buy_potential TEXT,
    hd_dep_count INT,
    hd_vehicle_count INT,
    PRIMARY KEY (hd_demo_sk)
);

CREATE TABLE is_keyspace.web_page (
    wp_web_page_sk INT,
    wp_web_page_id TEXT,
    wp_rec_start_date DATE,
    wp_rec_end_date DATE,
    wp_creation_date_sk INT,
    wp_access_date_sk INT,
    wp_autogen_flag TEXT,
    wp_customer_sk INT,
    wp_url TEXT,
    wp_type TEXT,
    wp_char_count INT,
    wp_link_count INT,
    wp_image_count INT,
    wp_max_ad_count INT,
    PRIMARY KEY (wp_web_page_sk)
);

CREATE TABLE is_keyspace.promotion (
    p_promo_sk INT,
    p_promo_id TEXT,
    p_start_date_sk INT,
    p_end_date_sk INT,
    p_item_sk INT,
    p_cost DECIMAL,
    p_response_target INT,
    p_promo_name TEXT,
    p_channel_dmail TEXT,
    p_channel_email TEXT,
    p_channel_catalog TEXT,
    p_channel_tv TEXT,
    p_channel_radio TEXT,
    p_channel_press TEXT,
    p_channel_event TEXT,
    p_channel_demo TEXT,
    p_channel_details TEXT,
    p_purpose TEXT,
    p_discount_active TEXT,
    PRIMARY KEY (p_promo_sk)
);

CREATE TABLE is_keyspace.catalog_page (
    cp_catalog_page_sk INT,
    cp_catalog_page_id TEXT,
    cp_start_date_sk INT,
    cp_end_date_sk INT,
    cp_department TEXT,
    cp_catalog_number INT,
    cp_catalog_page_number INT,
    cp_description TEXT,
    cp_type TEXT,
    PRIMARY KEY (cp_catalog_page_sk)
);

CREATE TABLE is_keyspace.inventory (
    inv_date_sk INT,
    inv_item_sk INT,
    inv_warehouse_sk INT,
    inv_quantity_on_hand INT,
    PRIMARY KEY (inv_date_sk, inv_item_sk, inv_warehouse_sk)
);

CREATE TABLE is_keyspace.catalog_returns (
    cr_returned_date_sk INT,
    cr_returned_time_sk INT,
    cr_item_sk INT,
    cr_refunded_customer_sk INT,
    cr_refunded_cdemo_sk INT,
    cr_refunded_hdemo_sk INT,
    cr_refunded_addr_sk INT,
    cr_returning_customer_sk INT,
    cr_returning_cdemo_sk INT,
    cr_returning_hdemo_sk INT,
    cr_returning_addr_sk INT,
    cr_call_center_sk INT,
    cr_catalog_page_sk INT,
    cr_ship_mode_sk INT,
    cr_warehouse_sk INT,
    cr_reason_sk INT,
    cr_order_number INT,
    cr_return_quantity INT,
    cr_return_amount DECIMAL,
    cr_return_tax DECIMAL,
    cr_return_amt_inc_tax DECIMAL,
    cr_fee DECIMAL,
    cr_return_ship_cost DECIMAL,
    cr_refunded_cash DECIMAL,
    cr_reversed_charge DECIMAL,
    cr_store_credit DECIMAL,
    cr_net_loss DECIMAL,
    PRIMARY KEY (cr_item_sk, cr_order_number)
);

CREATE TABLE is_keyspace.web_returns (
    wr_returned_date_sk INT,
    wr_returned_time_sk INT,
    wr_item_sk INT,
    wr_refunded_customer_sk INT,
    wr_refunded_cdemo_sk INT,
    wr_refunded_hdemo_sk INT,
    wr_refunded_addr_sk INT,
    wr_returning_customer_sk INT,
    wr_returning_cdemo_sk INT,
    wr_returning_hdemo_sk INT,
    wr_returning_addr_sk INT,
    wr_web_page_sk INT,
    wr_reason_sk INT,
    wr_order_number INT,
    wr_return_quantity INT,
    wr_return_amt DECIMAL,
    wr_return_tax DECIMAL,
    wr_return_amt_inc_tax DECIMAL,
    wr_fee DECIMAL,
    wr_return_ship_cost DECIMAL,
    wr_refunded_cash DECIMAL,
    wr_reversed_charge DECIMAL,
    wr_account_credit DECIMAL,
    wr_net_loss DECIMAL,
    PRIMARY KEY (wr_item_sk, wr_order_number)
);

CREATE TABLE is_keyspace.web_sales (
    ws_sold_date_sk INT,
    ws_sold_time_sk INT,
    ws_ship_date_sk INT,
    ws_item_sk INT,
    ws_bill_customer_sk INT,
    ws_bill_cdemo_sk INT,
    ws_bill_hdemo_sk INT,
    ws_bill_addr_sk INT,
    ws_ship_customer_sk INT,
    ws_ship_cdemo_sk INT,
    ws_ship_hdemo_sk INT,
    ws_ship_addr_sk INT,
    ws_web_page_sk INT,
    ws_web_site_sk INT,
    ws_ship_mode_sk INT,
    ws_warehouse_sk INT,
    ws_promo_sk INT,
    ws_order_number INT,
    ws_quantity INT,
    ws_wholesale_cost DECIMAL,
    ws_list_price DECIMAL,
    ws_sales_price DECIMAL,
    ws_ext_discount_amt DECIMAL,
    ws_ext_sales_price DECIMAL,
    ws_ext_wholesale_cost DECIMAL,
    ws_ext_list_price DECIMAL,
    ws_ext_tax DECIMAL,
    ws_coupon_amt DECIMAL,
    ws_ext_ship_cost DECIMAL,
    ws_net_paid DECIMAL,
    ws_net_paid_inc_tax DECIMAL,
    ws_net_paid_inc_ship DECIMAL,
    ws_net_paid_inc_ship_tax DECIMAL,
    ws_net_profit DECIMAL,
    PRIMARY KEY (ws_item_sk, ws_order_number)
);

CREATE TABLE is_keyspace.catalog_sales (
    cs_sold_date_sk INT,
    cs_sold_time_sk INT,
    cs_ship_date_sk INT,
    cs_bill_customer_sk INT,
    cs_bill_cdemo_sk INT,
    cs_bill_hdemo_sk INT,
    cs_bill_addr_sk INT,
    cs_ship_customer_sk INT,
    cs_ship_cdemo_sk INT,
    cs_ship_hdemo_sk INT,
    cs_ship_addr_sk INT,
    cs_call_center_sk INT,
    cs_catalog_page_sk INT,
    cs_ship_mode_sk INT,
    cs_warehouse_sk INT,
    cs_item_sk INT,
    cs_promo_sk INT,
    cs_order_number INT,
    cs_quantity INT,
    cs_wholesale_cost DECIMAL,
    cs_list_price DECIMAL,
    cs_sales_price DECIMAL,
    cs_ext_discount_amt DECIMAL,
    cs_ext_sales_price DECIMAL,
    cs_ext_wholesale_cost DECIMAL,
    cs_ext_list_price DECIMAL,
    cs_ext_tax DECIMAL,
    cs_coupon_amt DECIMAL,
    cs_ext_ship_cost DECIMAL,
    cs_net_paid DECIMAL,
    cs_net_paid_inc_tax DECIMAL,
    cs_net_paid_inc_ship DECIMAL,
    cs_net_paid_inc_ship_tax DECIMAL,
    cs_net_profit DECIMAL,
    PRIMARY KEY (cs_item_sk, cs_order_number)
);

CREATE TABLE is_keyspace.store_sales (
    ss_sold_date_sk INT,
    ss_sold_time_sk INT,
    ss_item_sk INT,
    ss_customer_sk INT,
    ss_cdemo_sk INT,
    ss_hdemo_sk INT,
    ss_addr_sk INT,
    ss_store_sk INT,
    ss_promo_sk INT,
    ss_ticket_number INT,
    ss_quantity INT,
    ss_wholesale_cost DECIMAL,
    ss_list_price DECIMAL,
    ss_sales_price DECIMAL,
    ss_ext_discount_amt DECIMAL,
    ss_ext_sales_price DECIMAL,
    ss_ext_wholesale_cost DECIMAL,
    ss_ext_list_price DECIMAL,
    ss_ext_tax DECIMAL,
    ss_coupon_amt DECIMAL,
    ss_net_paid DECIMAL,
    ss_net_paid_inc_tax DECIMAL,
    ss_net_profit DECIMAL,
    PRIMARY KEY (ss_item_sk, ss_ticket_number)
);