services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ${MONGO_DATA_LOCAL_PATH}:/data/db
    networks:
      - presto-net

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ${CASSANDRA_DATA_LOCAL_PATH}:/var/lib/cassandra
      - ${TEST_DATA_TMP_LOCAL_PATH}:/tmp/data
    networks:
      - presto-net

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ${POSTGRES_DATA_LOCAL_PATH}:/var/lib/postgresql/data
    networks:
      - presto-net

  prestodb:
    image: prestodb/presto:latest
    container_name: prestodb
    ports:
      - "8080:8080"
    volumes:
      - ${PRESTO_CATALOG_LOCAL_PATH}:/opt/presto-server/etc/catalog
    depends_on:
      - mongo
      - cassandra
      - postgres
    networks:
      - presto-net

volumes:
  mongo-data:
  cassandra-data:
  postgres-data:

networks:
  presto-net:
